### ISSUE TITLE
Suggest to set reclaimPolicy Retain on datadir PV

### ISSUE THREAD

**Issue by camuffo** [geosolutions-it/charts#28]
The README should mention that StorageClasses usually provision PVs with `reclaimPolicy: Delete`.
Suggest to manually patch the reclaimPolicy to be `Retain`, to preserve valuable data.

```
kubectl -n gs patch pv PV_NAME -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'
```

**Comment by randomorder** [comment]
Hi @camuffo 

Please try this instead:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

the use of annotations to prevent PVC deletion on unistall. Also test what happens on reinstall / upgrade. Do the PVCs reattach to the PODs automatically?
